services:
  rpxy-rp:
    image: jqtype/rpxy:latest # ghcr.io/junkurihara/rust-rpxy:latest also works
    container_name: rpxy
    init: true
    restart: unless-stopped
    ports:
      - 0.0.0.0:443:443/tcp
      - 0.0.0.0:443:443/udp
    build: # Uncomment if you build yourself
      context: ../
      args:
         - "CARGO_FEATURES=--no-default-features --features=http3-quinn,webpki-roots"
      dockerfile: ./docker/rpxy-Dockerfile # based on ubuntu 22.04 and build x86_64-unknown-linux-gnu
      platforms: # Choose your platforms
        # - "linux/amd64"
        - "linux/arm64"
    environment:
      - LOG_LEVEL=debug
      - LOG_TO_FILE=true
      - HOST_USER=jun
      - HOST_UID=501
      - HOST_GID=501
      # - WATCH=true
    tty: false
    privileged: true
    volumes:
      - ./log:/rpxy/log:rw
      - ./cache:/rpxy/cache:rw
      - ./acme_registry:/rpxy/acme_registry:rw
      - ../config.toml:/etc/rpxy.toml:ro

  tlsnotary:
    image: jqtype/rpxy:latest # ghcr.io/junkurihara/rust-rpxy:latest also works
    container_name: tlsnotary
    init: true
    restart: unless-stopped
    ports:
      - 127.0.0.1:7047:7047/tcp
    build: # Uncomment if you build yourself
      context: ../submodules/tlsn
      args:
          - "CARGO_FEATURES=--features=tee_quote"
      dockerfile: ./docker/tlsnotary-Dockerfile # based on ubuntu 22.04 and build x86_64-unknown-linux-gnu
      platforms: # Choose your platforms
         - "linux/amd64"
    environment:
      - LOG_LEVEL=debug
    tty: false
    privileged: false
    volumes:
      - ./log:/rpxy/log:rw
      - ./cache:/rpxy/cache:rw
      - ./acme_registry:/rpxy/acme_registry:rw
      - ../submodules/tlsn/crates/notary/server/config:/workspace:ro
      - ../submodules/tlsn/crates/notary/server/fixture:/workspace:ro
